[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=pymstdncollect --cov-report=html --cov-config=.coveragerc --import-mode=importlib"
testpaths = [
    "test",
]